#!/bin/bash

guest_name="$1"
libvirt_task="$2"

# 获取脚本所在的目录
script_dir=$(dirname "$(readlink -f "$BASH_SOURCE")")

cd "$script_dir"
./qemu.py "$guest_name" "$libvirt_task"# >> /var/log/libvirt/hooks.log 2>&1
