#!/bin/bash

guest_name="$1"
libvirt_task="$2"

if [[ $guest_name == "win11" || $guest_name == "win10" || $guest_name == "ubuntu" || $guest_name == "vArch" || $guest_name == "android" || $guest_name == "docker_arch" ]] ; then
	case "$libvirt_task" in
        	"prepare")

                /usr/bin/data_snap.sh jdata/vdisk/ $guest_name 2>&1 | tee -a /var/log/libvirt/custom_hooks.log

                # video card passthrough
                if [[ $guest_name == "win11" || $guest_name == "win10" || $guest_name == "ubuntu" || $guest_name == "vArch" ]] ; then
                    pkill -15 xinit 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
                    sleep 5

                    # /bin/vfio-startup.sh 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
                fi
                ;;

            "release")
                # if [[ $guest_name == "win11" || $guest_name == "win10" || $guest_name == "ubuntu" || $guest_name == "vArch" ]] ; then
                #    /bin/vfio-teardown.sh 2>&1 | tee -a /var/log/libvirt/custom_hooks.log
                # fi
                ;;
	esac
fi
